#consul服务端口号
server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  #consul住
  cloud:
    consul:
      host: 192.168.1.203
      port: 8500
      discovery:
        hostname: 192.168.1.133
        service-name: ${spring.application.name}

